### ISSUE TITLE
Step 2 - Tutorial issues/enhancements

### ISSUE THREAD

**Issue by kevindavi5** [hydrateio/advanced-graphql-server-tutorial#16]
[ ] - add 's' to typeDef and 'r' to resolves “remove all typeDef and resolves from”
[ ] - mention what extension is being using for syntax highlighting since /* GraphQL */ before the template string is unique.
[ ] - In the Consolidate Extracted Schemas section “Since we will be defining Query types in multiple locations, we will update our checkout.typeDef.js file to extend the Query type”. The code snippet above already included `extend type Query`. We should fix this so that it’s `type Query` initially and have them add extend if that’s what we want them to do here.
[ ] - “In later tutorials, we will be Mutations and Subscriptions to our project” need to add “we will be adding* Mutations and Subscriptions”
[ ] - we should probably get them to install graphql-tools and lodash.merge before modifying schema/index.js
[ ] - need to update code snippet query from user_email: to userEmail
[ ] - “and return the same set of 4 results.” it currently returns 5

**Comment by natergj** [comment]
IDE plugins would be a great addition to the Resources section. I'm using https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo but there are many more that will do syntax highlighting for the commented template string.

**Comment by natergj** [comment]
The Step 2 docs do have "There are two libraries that we will install to assist us in this step: graphql-tools and lodash.merge." before the `schema/index.js` code snippet. Since this is an advanced tutorial, my thoughts are that we could leave out the instruction on how to do that.

**Comment by natergj** [comment]
The `extend type Query` is there to handle the later section when we define the empty `Query` typeDef in the `schema/index.js` file. It should definitely be highlighted that it was added when extracting the typeDefs into their own files.  We could either leave the code snippet as is, add a `<mark>` tag around `extend` and include an extra line in the instructions as to why it was added or create a new code snippet for the updated after showing the `schema/index.js` file. I'm not sure if one is better than the other, I'm fine either way.

**Comment by kevindavi5** [comment]
> The Step 2 docs do have "There are two libraries that we will install to assist us in this step: graphql-tools and lodash.merge." before the `schema/index.js` code snippet. Since this is an advanced tutorial, my thoughts are that we could leave out the instruction on how to do that.

My thought was that it wasn't so much a how but simply part of the process. If they've started from the beginning without checking out the current step's branch then they will need those libraries installed to use them.
