### ISSUE TITLE
Step 4 - Enhancements

### ISSUE THREAD

**Issue by kevindavi5** [hydrateio/advanced-graphql-server-tutorial#19]
The `Create the MongoDB Connector` section could contain more details about setting up the env. Linking to the file is good but if the user started from the step-0 branch and added in the mongodb connector file they would still need to install mongodb and update the env files.

[ ] - no mention of installing ‘mongodb’
[ ] - no mention of updating src/env.js
[ ] - no mention of updating .env

**Comment by natergj** [comment]
Immediately before the "Create the MongoDB Connector" section, there is a note about installing the mongo driver with a link to the npmjs page. I was thinking of the best way to handle step by step installs. Describing that a user needs to install updates every time a new library is added may get a bit redundant. Thoughts on adding a note to the "Getting Started" section stating that each step may include new libraries that need to be installed to continue? If this was a beginners tutorial, I may be inclined to explicitly add library install snippets for each new library.

I agree that there should at least be mention of updating the env files for this step. possibly adding that to the "Create the MongoDB Connector" section as well?
